import type { Match, Prediction, Profile, StageState, Team } from "./types";

export const teams: Team[] = [
  { id: "arg", name: "Argentina", shortName: "ARG", flag: "🇦🇷", group: "A" },
  { id: "mex", name: "México", shortName: "MEX", flag: "🇲🇽", group: "A" },
  { id: "usa", name: "Estados Unidos", shortName: "USA", flag: "🇺🇸", group: "B" },
  { id: "can", name: "Canadá", shortName: "CAN", flag: "🇨🇦", group: "B" },
  { id: "bra", name: "Brasil", shortName: "BRA", flag: "🇧🇷", group: "C" },
  { id: "esp", name: "España", shortName: "ESP", flag: "🇪🇸", group: "C" },
  { id: "fra", name: "Francia", shortName: "FRA", flag: "🇫🇷", group: "D" },
  { id: "uru", name: "Uruguay", shortName: "URU", flag: "🇺🇾", group: "D" },
];

export const profiles: Profile[] = [
  { id: "u1", displayName: "Manu", email: "manu@example.com", approved: true, role: "admin" },
  { id: "u2", displayName: "Sofía", email: "sofia@example.com", approved: true, role: "user" },
  { id: "u3", displayName: "Diego", email: "diego@example.com", approved: true, role: "user" },
  { id: "u4", displayName: "Vero", email: "vero@example.com", approved: true, role: "user" },
  { id: "u5", displayName: "Luli", email: "luli@example.com", approved: false, role: "user" },
];

export const stages: StageState[] = [
  { stage: "groups", label: "Grupos", open: true },
  { stage: "round32", label: "16avos", open: false },
  { stage: "round16", label: "Octavos", open: false },
  { stage: "quarter", label: "Cuartos", open: false },
  { stage: "semi", label: "Semis", open: false },
  { stage: "third", label: "3er puesto", open: false },
  { stage: "final", label: "Final", open: false },
];

export const matches: Match[] = [
  {
    id: "m1",
    matchNo: 1,
    stage: "groups",
    group: "A",
    homeTeamId: "arg",
    awayTeamId: "mex",
    kickoffUtc: "2026-06-11T22:00:00.000Z",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    status: "open",
    homeScore: null,
    awayScore: null,
    winnerTeamId: null,
    finalizedAt: null,
    finalizedBy: null,
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: "m2",
    matchNo: 2,
    stage: "groups",
    group: "B",
    homeTeamId: "usa",
    awayTeamId: "can",
    kickoffUtc: "2026-06-07T10:00:00.000Z",
    venue: "Lumen Field",
    city: "Seattle",
    status: "live",
    homeScore: null,
    awayScore: null,
    winnerTeamId: null,
    finalizedAt: null,
    finalizedBy: null,
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: "m3",
    matchNo: 3,
    stage: "groups",
    group: "C",
    homeTeamId: "bra",
    awayTeamId: "esp",
    kickoffUtc: "2026-06-06T22:00:00.000Z",
    venue: "Hard Rock Stadium",
    city: "Miami",
    status: "finalized",
    homeScore: 2,
    awayScore: 1,
    winnerTeamId: null,
    finalizedAt: "2026-06-07T00:15:00.000Z",
    finalizedBy: "u1",
    updatedAt: "2026-06-07T00:15:00.000Z",
    updatedBy: "u1",
  },
  {
    id: "m4",
    matchNo: 49,
    stage: "round16",
    homeTeamId: "arg",
    awayTeamId: "fra",
    homeSeed: "1A",
    awaySeed: "2B",
    kickoffUtc: "2026-06-12T01:00:00.000Z",
    venue: "MetLife Stadium",
    city: "New York/New Jersey",
    status: "open",
    homeScore: null,
    awayScore: null,
    winnerTeamId: null,
    finalizedAt: null,
    finalizedBy: null,
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: "m5",
    matchNo: 57,
    stage: "quarter",
    homeTeamId: null,
    awayTeamId: null,
    homeSeed: "Ganador Octavos 1",
    awaySeed: "Ganador Octavos 2",
    kickoffUtc: "2026-07-10T01:00:00.000Z",
    venue: "AT&T Stadium",
    city: "Dallas",
    status: "open",
    homeScore: null,
    awayScore: null,
    winnerTeamId: null,
    finalizedAt: null,
    finalizedBy: null,
    updatedAt: null,
    updatedBy: null,
  },
];

export const predictions: Prediction[] = [
  {
    id: "p1",
    userId: "u1",
    matchId: "m1",
    homeScore: 2,
    awayScore: 0,
    winnerTeamId: null,
    points: null,
    exactHit: false,
    outcomeHit: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-07T19:00:00.000Z",
  },
  {
    id: "p2",
    userId: "u1",
    matchId: "m2",
    homeScore: 1,
    awayScore: 1,
    winnerTeamId: null,
    points: null,
    exactHit: false,
    outcomeHit: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-07T09:00:00.000Z",
  },
  {
    id: "p3",
    userId: "u2",
    matchId: "m2",
    homeScore: 2,
    awayScore: 1,
    winnerTeamId: null,
    points: null,
    exactHit: false,
    outcomeHit: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-07T08:45:00.000Z",
  },
  {
    id: "p4",
    userId: "u1",
    matchId: "m3",
    homeScore: 2,
    awayScore: 1,
    winnerTeamId: null,
    points: 3,
    exactHit: true,
    outcomeHit: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-06T20:00:00.000Z",
  },
  {
    id: "p5",
    userId: "u2",
    matchId: "m3",
    homeScore: 1,
    awayScore: 0,
    winnerTeamId: null,
    points: 1,
    exactHit: false,
    outcomeHit: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-06T20:00:00.000Z",
  },
  {
    id: "p6",
    userId: "u1",
    matchId: "m4",
    homeScore: 1,
    awayScore: 1,
    winnerTeamId: "arg",
    points: null,
    exactHit: false,
    outcomeHit: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-07T20:00:00.000Z",
  },
];
