-- Seed all 48 FIFA World Cup 2026 teams referenced by docs/worldcup2026-fixture.csv.
-- Run this BEFORE importing the fixture CSV, otherwise the matches FK
-- constraints (matches_home_team_id_fkey / matches_away_team_id_fkey) fail.
insert into public.teams (id, name, short_name, flag, group_label) values
  ('cze', 'Czech Republic', 'CZE', '🇨🇿', 'A'),
  ('kor', 'South Korea', 'KOR', '🇰🇷', 'A'),
  ('mex', 'Mexico', 'MEX', '🇲🇽', 'A'),
  ('rsa', 'South Africa', 'RSA', '🇿🇦', 'A'),
  ('bih', 'Bosnia and Herzegovina', 'BIH', '🇧🇦', 'B'),
  ('can', 'Canada', 'CAN', '🇨🇦', 'B'),
  ('qat', 'Qatar', 'QAT', '🇶🇦', 'B'),
  ('sui', 'Switzerland', 'SUI', '🇨🇭', 'B'),
  ('bra', 'Brazil', 'BRA', '🇧🇷', 'C'),
  ('hai', 'Haiti', 'HAI', '🇭🇹', 'C'),
  ('mar', 'Morocco', 'MAR', '🇲🇦', 'C'),
  ('sco', 'Scotland', 'SCO', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'C'),
  ('aus', 'Australia', 'AUS', '🇦🇺', 'D'),
  ('par', 'Paraguay', 'PAR', '🇵🇾', 'D'),
  ('tur', 'Turkey', 'TUR', '🇹🇷', 'D'),
  ('usa', 'United States', 'USA', '🇺🇸', 'D'),
  ('civ', 'Ivory Coast', 'CIV', '🇨🇮', 'E'),
  ('cuw', 'Curaçao', 'CUW', '🇨🇼', 'E'),
  ('ecu', 'Ecuador', 'ECU', '🇪🇨', 'E'),
  ('ger', 'Germany', 'GER', '🇩🇪', 'E'),
  ('jpn', 'Japan', 'JPN', '🇯🇵', 'F'),
  ('ned', 'Netherlands', 'NED', '🇳🇱', 'F'),
  ('swe', 'Sweden', 'SWE', '🇸🇪', 'F'),
  ('tun', 'Tunisia', 'TUN', '🇹🇳', 'F'),
  ('bel', 'Belgium', 'BEL', '🇧🇪', 'G'),
  ('egy', 'Egypt', 'EGY', '🇪🇬', 'G'),
  ('irn', 'Iran', 'IRN', '🇮🇷', 'G'),
  ('nzl', 'New Zealand', 'NZL', '🇳🇿', 'G'),
  ('cpv', 'Cape Verde', 'CPV', '🇨🇻', 'H'),
  ('esp', 'Spain', 'ESP', '🇪🇸', 'H'),
  ('ksa', 'Saudi Arabia', 'KSA', '🇸🇦', 'H'),
  ('uru', 'Uruguay', 'URU', '🇺🇾', 'H'),
  ('fra', 'France', 'FRA', '🇫🇷', 'I'),
  ('irq', 'Iraq', 'IRQ', '🇮🇶', 'I'),
  ('nor', 'Norway', 'NOR', '🇳🇴', 'I'),
  ('sen', 'Senegal', 'SEN', '🇸🇳', 'I'),
  ('alg', 'Algeria', 'ALG', '🇩🇿', 'J'),
  ('arg', 'Argentina', 'ARG', '🇦🇷', 'J'),
  ('aut', 'Austria', 'AUT', '🇦🇹', 'J'),
  ('jor', 'Jordan', 'JOR', '🇯🇴', 'J'),
  ('cod', 'Democratic Republic of the Congo', 'COD', '🇨🇩', 'K'),
  ('col', 'Colombia', 'COL', '🇨🇴', 'K'),
  ('por', 'Portugal', 'POR', '🇵🇹', 'K'),
  ('uzb', 'Uzbekistan', 'UZB', '🇺🇿', 'K'),
  ('cro', 'Croatia', 'CRO', '🇭🇷', 'L'),
  ('eng', 'England', 'ENG', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'L'),
  ('gha', 'Ghana', 'GHA', '🇬🇭', 'L'),
  ('pan', 'Panama', 'PAN', '🇵🇦', 'L')
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  flag = excluded.flag,
  group_label = excluded.group_label;
